@startuml

!theme reddress-darkblue
skinparam BackgroundColor lavender
skinparam ArrowColor black
skinparam ArrowThickness 1.0
skinparam RoundCorner 7
skinparam ClassAttributeFontColor FFFFFF
skinparam ClassFontSize 12
skinparam ArrowFontColor black

!include clase_detective.plantuml
!include clase_tiempoRestante.plantuml
!include clase_ciudad.plantuml
!include clase_edificio.plantuml
!include clase_pista.plantuml

Detective "1" *-down->"1" TiempoRestante
Detective "1" *-down->"1" Ciudad
Ciudad "1" *-down->"3" Edificio
Edificio "1" *-down->"1" Pista
Ciudad -->"1" Ciudad

Edificio ..> Ciudad
Ciudad ..> TiempoRestante
@enduml