@startuml

!theme reddress-darkblue
skinparam BackgroundColor lavender
skinparam ArrowColor black
skinparam ArrowThickness 1.0
skinparam RoundCorner 7
skinparam ClassAttributeFontColor FFFFFF
skinparam ClassFontSize 12
skinparam ArrowFontColor black

Class Pistas{

    + pistaFacil():Pista
    + pistaIntermedia(): Pista
    + pistaDificil(): Pista

}

@enduml