@startuml

!theme reddress-darkblue
autonumber
skinparam style strictuml
skinparam BackGroundColor white
skinparam RoundCorner 7
skinparam SequenceGroupFontColor black
skinparam SequenceGroupBorderColor black
skinparam SequenceGroupBorderThickness 0.5
skinparam ArrowFontColor black
skinparam ArrowColor black
skinparam ActorFontColor black
skinparam participantFontSize 12
skinparam SequenceLifeLineBackGroundColor 2e2e2e
loop 55 visitas
TestCase -> "novato:Policia" as policia: visitarEdificio(puerto:EdificioTransporte)

policia -> "Montreal:Ciudad" as montreal : visitarEdificio(puerto, novato:Rango, tiempo:TiempoRestante)

montreal ->"puerto: EdificioTransporte" as edificio: serVisitado(proximaCiudad:Ciudad, novato:Rango, tiempo:TiempoRestante, numeroVisita:Integer)
edificio -> "proximaCiudad:Ciudad" as proximaCiudad : pistaAeropuerto(novato:Rango)
proximaCiudad -> "novato:Rango" as rango : pedirPista(pistasBanco:Pistas, ladron:Ladron)
rango --> proximaCiudad: pistasDevueltas
proximaCiudad -->edificio : pistasDevueltas

montreal <-- edificio: pistasDevueltas
montreal -> montreal : sumarVisita()
policia <-- montreal: pistasDevueltas
policia --> TestCase: pistasDevueltas
end

@enduml