@startuml

!theme reddress-darkblue
autonumber
skinparam style strictuml
skinparam BackGroundColor white
skinparam RoundCorner 7
skinparam SequenceGroupFontColor black
skinparam SequenceGroupBorderColor black
skinparam SequenceGroupBorderThickness 0.5
skinparam ArrowFontColor black
skinparam ArrowColor black
skinparam ActorFontColor black
skinparam participantFontSize 12
skinparam SequenceLifeLineBackGroundColor 2e2e2e

TestCase -> "policia:Policia" as policia: dormir()
policia -> "tiempo:Tiempo" as tiempo: dormir
tiempo ->tiempo : sumarHoras(8)
TestCase -> policia : herirConCuchillo()
policia -> tiempo : herirConCuchillo()
tiempo->tiempo : sumarHoras(2)


@enduml