@startuml
class AlgoThief{
    + new(fachada:ObtenerDatosFachada)
}

class ObtenerDatosFachada{

    + new(lectorCiudades:Lector, lectorLadrones:Lector, lectorObjetosRobados:Lector, lectorPolicias:Lector)

    + obtenerCiudades():ArrayList
    + obtenerLadrones():ArrayList
    + obtenerObjetos():ArrayList
    + obtenerPolicias():ArrayList

}

interface Lector{
    + leer(): ArrayList
}

class LectorJsonCiudades{
}

class LectorJsonLadrones{}

class LectorJsonPolicias{}

class LectorJsonObjetos{}

AlgoThief -down->"1" ObtenerDatosFachada
ObtenerDatosFachada -down->"4" Lector
LectorJsonCiudades .up.|> Lector
LectorJsonLadrones .up.|> Lector
LectorJsonLadrones .up.|> Lector
LectorJsonPolicias .up.|> Lector
LectorJsonObjetos .up.|> Lector
@enduml