@startuml
!theme reddress-darkblue
autonumber
skinparam style strictuml
skinparam BackGroundColor lavender
skinparam RoundCorner 7
skinparam SequenceGroupFontColor black
skinparam SequenceGroupBorderColor black
skinparam SequenceGroupBorderThickness 0.5
skinparam ArrowFontColor black
skinparam ArrowColor black
skinparam ActorFontColor black
skinparam participantFontSize 12
skinparam SequenceLifeLineBackGroundColor 2e2e2e

TestCase -> "detective:Detective" as detective : visitarEdificio(nombreEdificio:String)
detective -> "visita:Visita" as visita: visitarEdificio(nombreEdificio)
visita -> ":Pais" as pais: visitarEdificio(nombreEdificio)
pais -> "edificio:Edificio" as edificio: serVisitado()
pais <-- edificio : pista
pais --> visita : pista
visita --> detective : pista

detective -> visita: restarHoras(tiempo:Tiempo)
visita -> "tiempo:Tiempo" as tiempo : restarHoras(1)

detective --> TestCase : pista

@enduml